Feature 96 creatorviewpage 01
SeattleColleges/nsc-events-android pull request #111
Opened 2023-11-08 06:53 UTC by Ali-7s

Draft PR

2023-11-10 18:44 UTC, Robel-003 requested changes
This looks good. 
_View All Events_ is currently routing to the add event page. We want both _View My Event_ and _View All Events_ to route back to the home page where all the events are. (_View My Event_ will eventually be filtered for only the Creator’s events)

Let’s also add a back arrow from the _Creator View_ page that takes us back to the previous page which would be the home page.

And let’s change the home page _Sign-up_ button to say _Creator’s View_. We’ll eventually change it, but at the moment it’s a bit confusing to have two sign-up buttons

2023-11-15 06:35 UTC, bcko commented
Let us know when this pull request is ready for review @Ali-7s

2023-11-15 07:22 UTC, taylorpapke approved these changes

2023-11-15 07:26 UTC, taylorpapke commented
Looks like the requested changes have been incorporated. Back button has been added, create event routes to add event page, view all events and view my events route back to home page. Home page Sign-up button now says Creator View.

2023-11-15 11:33 UTC, bcko approved these changes

2023-11-15 11:33 UTC, merged