nsc-event-android-1-52-Event-DTO
SeattleColleges/nsc-events-android pull request #77
Opened 2023-10-20 22:41 UTC by TroyFPV48

Resolves #52

2023-10-22 20:51 UTC, taylorpapke commented on app/src/main/java/com/example/nsc_events/screen/AddEvent.kt
> +    var eventEndDate by remember { mutableStateOf(Calendar.getInstance().time) }
I believe startDate and endDate should use String and be relabeled to startTime and endTime to match the name and type in our schema https://github.com/SeattleColleges/nsc-events-nestjs/blob/main/src/activity/schemas/activity.schema.ts

2023-10-22 20:54 UTC, taylorpapke commented on app/src/main/java/com/example/nsc_events/data/Event.kt
> +    val eventEndTime: Date,
I believe eventStartTime and eventEndTime should be changed to String type to match our schema https://github.com/SeattleColleges/nsc-events-nestjs/blob/main/src/activity/schemas/activity.schema.ts

2023-10-22 21:08 UTC, taylorpapke requested changes
Overall looks great but after testing, I noticed that the back button to the login screen has a text field overlapping it which makes it hard to click:
<img width="188" alt="Screenshot 2023-10-22 at 1 57 49 PM" src="https://github.com/SeattleColleges/nsc-events-android/assets/94101953/8f85f772-1965-4462-902c-bc1038dcc765">
I also noticed that some of the data types in nestjs are type String[] but we are using String here. @theGaryLarson is this fine for now or do you want us to start implementing the String[] right away?

2023-10-28 06:50 UTC, theGaryLarson commented
> Overall looks great but after testing, I noticed that the back button to the login screen has a text field overlapping it which makes it hard to click: <img alt="Screenshot 2023-10-22 at 1 57 49 PM" width="188" src="https://user-images.githubusercontent.com/94101953/277192267-8f85f772-1965-4462-902c-bc1038dcc765.png"> I also noticed that some of the data types in nestjs are type String[] but we are using String here. @theGaryLarson is this fine for now or do you want us to start implementing the String[] right away?


The following attributes need to be String arrays:
* eventTags
* eventSpeakers

@TroyFPV48  please make these requested changes so we can approve, thanks.

2023-10-28 22:15 UTC, TroyFPV48 commented
sure I will fix the String elements again!

2023-11-01 23:15 UTC, taylorpapke commented
@TroyFPV48 let's also not forget to resolve the conflicts on this so we can get it merged in.

2023-11-02 03:48 UTC, TroyFPV48 commented
> > > Overall looks great but after testing, I noticed that the back button to the login screen has a text field overlapping it which makes it hard to click:
> > 
> > 
> > <img alt="Screenshot 2023-10-22 at 1 57 49 PM" width="188" src="https://user-images.githubusercontent.com/94101953/277192267-8f85f772-1965-4462-902c-bc1038dcc765.png">
> > I also noticed that some of the data types in nestjs are type String[] but we are using String here. @theGaryLarson is this fine for now or do you want us to start implementing the String[] right away?
> > We can probably trim some of these attributes of event. @Robel-003 what were the main things that they have asked tracked. I was thinking just the basics for now. Once everything is connected and functioning it will not be too difficult to come and add in additional attributes.
> > The following attributes need to be String arrays:
> > 
> > * eventTags
> > 
> > @TroyFPV48 please make these requested changes so we can approve, thanks.
> 
> In addition to the fields, they wanted a date, location, and an option to insert a flier or image, like an attach image button

Sorry, I wasn't cleared. Which fields specifically need attachable items?

2023-11-02 06:33 UTC, taylorpapke commented
@Robel-003 what do you think? Can we waive the attachable items on this PR and get it on the next one since this is getting to be a fairly large merge?

2023-11-04 22:43 UTC, TroyFPV48 reviewed
I have fixed the conflicts, please review this PR.

2023-11-04 23:39 UTC, Robel-003 commented
> I have fixed the conflicts, please review this PR.

hey @TroyFPV48, it's still showing unresolved conflicts in the Event.kt and AddEvent.kt files

2023-11-05 22:57 UTC, taylorpapke commented
@TroyFPV48 helpful doc on resolving merge conflicts: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

2023-11-06 08:22 UTC, taylorpapke approved these changes

2023-11-06 23:30 UTC, Robel-003 approved these changes
This looks good. I like the calendar options for date selections and I'm able to see the back arrow for the Login page

2023-11-06 23:43 UTC, merged